apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o ../k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: embedder
  name: embedder
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: embedder
