apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o ../k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3000
  selector:
    io.kompose.service: grafana
