apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o ../k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: pyroscope
  name: pyroscope
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pyroscope
  template:
    metadata:
      labels:
        io.kompose.service: pyroscope
    spec:
      containers:
        - args:
            - server
          env:
            - name: PYROSCOPE_STORAGE_PATH
              value: /var/lib/pyroscope
          image: pyroscope/pyroscope:latest
          name: semki-pyroscope
          ports:
            - containerPort: 4040
              protocol: TCP
      restartPolicy: Always
